#!/bin/bash

GETH_DEFAULT_PORT=8545
GETH_SECONDARY_PORT=8546
NETWORK_ID=1337
TRANSEPTOR_ENTRYPOINT_ADDRESS_V8=""
TRANSEPTOR_BENEFICIARY="0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
DEV_MNEMONIC="test test test test test test test test test test test junk"
DEV_ACCOUNT_3_PRIVATE_KEY="0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6" # private key from the junk SRP to deploy the contract

start_geth_with_erc7562_native_tracer() {
  # first 4 accounts default hardhat accounts
  DEFAULT_ADDRESS_0="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" # bundler signer
  DEFAULT_ADDRESS_1="0x70997970C51812dc3A010C7d01b50e0d17dc79C8" # local e2e runner
  DEFAULT_ADDRESS_2="0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC" # bundler beneficiary
  DEFAULT_ADDRESS_3="0x90F79bf6EB2c4f870365E785982E1f101E93b906" # contract deployed

  if docker ps -a | grep -q geth-with-erc7562-tracer-transeptor; then
    echo -e "Removing existing geth container\n"
    docker rm -f geth-with-erc7562-tracer-transeptor
  fi

  geth_with_erc7562_tracer_container_id=$(docker run -d --name geth-with-erc7562-tracer-transeptor -p $GETH_DEFAULT_PORT:$GETH_DEFAULT_PORT accountabstraction/geth-with-erc7562-tracer \
    --verbosity 1 \
    --http.vhosts '*,localhost,host.docker.internal'\
    --http \
    --http.port $GETH_DEFAULT_PORT \
    --http.api eth,net,web3,debug \
    --http.corsdomain '*' \
    --http.addr "0.0.0.0" \
    --networkid  $NETWORK_ID \
    --dev \
    --dev.period 0 \
    --maxpeers 0 \
    --nodiscover \
    --allow-insecure-unlock \
    --rpc.allow-unprotected-txs \
    --dev.gaslimit  12000000 )

  sleep 4

  echo -e "Account balances(Defaults):"
  for ACCOUNT in $DEFAULT_ADDRESS_0 $DEFAULT_ADDRESS_1 $DEFAULT_ADDRESS_2 $DEFAULT_ADDRESS_3; do
    isSigner=" (Default account)"
    if [ "$ACCOUNT" == "$DEFAULT_ADDRESS_0" ]; then
      isSigner=" (Default account: Bundler signer account)"
    fi

    docker exec $geth_with_erc7562_tracer_container_id geth \
      --exec "eth.sendTransaction({from: eth.accounts[0], to: \"$ACCOUNT\", value: web3.toWei(4337, \"ether\")})" \
      attach http://localhost:$GETH_DEFAULT_PORT/ > /dev/null
    
    balance=$(docker exec $geth_with_erc7562_tracer_container_id geth --exec "eth.getBalance(\"$ACCOUNT\")" attach http://localhost:$GETH_DEFAULT_PORT/)
    echo -e "  - $ACCOUNT$isSigner: $balance wei"
  done
  echo -e "\n"

  echo -e "ERC 4337 contracts:"
  cd ./contracts
  forge build --evm-version cancun
  OUTPUT=$(forge script ./scripts/DeployBundlerDev.s.sol --rpc-url http://localhost:$GETH_DEFAULT_PORT --broadcast --private-key $DEV_ACCOUNT_3_PRIVATE_KEY) 
  TRANSEPTOR_ENTRYPOINT_ADDRESS_V8=$(echo "$OUTPUT" | grep -o "EntryPoint: 0x[0-9a-fA-F]*" | cut -d' ' -f2)
  TRANSEPTOR_E2E_SIMPLE_ACCOUNT_FACTORY=$(echo "$OUTPUT" | grep -o "SimpleAccountFactory: 0x[0-9a-fA-F]*" | cut -d' ' -f2)
  TRANSEPTOR_E2E_GLOBAL_COUNTER=$(echo "$OUTPUT" | grep -o "GlobalCounter: 0x[0-9a-fA-F]*" | cut -d' ' -f2)
  echo -e "$(tput setaf 4)▼▼▼ $(tput setaf 7)Please add to local .env$(tput setaf 4) ▼▼▼$(tput sgr0)\n
  TRANSEPTOR_MNEMONIC=$DEV_MNEMONIC
  TRANSEPTOR_ENTRYPOINT_ADDRESS=$TRANSEPTOR_ENTRYPOINT_ADDRESS_V8
  TRANSEPTOR_BENEFICIARY=$TRANSEPTOR_BENEFICIARY\n
  TRANSEPTOR_E2E_SIMPLE_ACCOUNT_FACTORY=$TRANSEPTOR_E2E_SIMPLE_ACCOUNT_FACTORY
  TRANSEPTOR_E2E_GLOBAL_COUNTER=$TRANSEPTOR_E2E_GLOBAL_COUNTER
  TRANSEPTOR_E2E_TRANSEPTOR_MNEMONIC=$DEV_MNEMONIC
  TRANSEPTOR_E2E_CHAIN_ID=$NETWORK_ID
  TRANSEPTOR_E2E_NETWORK_PROVIDER_URL=http://localhost:$GETH_DEFAULT_PORT
  TRANSEPTOR_E2E_BUNDLER_URL=http://localhost:4337/rpc
  TRANSEPTOR_E2E_MIN_SENDER_DEPOSIT=2
  $(tput setaf 6)────────────────────────────────────────────────────────$(tput sgr0)\n"
}

start_geth() {
  if docker ps -a | grep -q geth-transeptor; then
    echo -e "Removing existing geth-transeptor container\n"
    docker rm -f geth-transeptor
  fi

  geth_container_id=$(docker run -d --name geth-transeptor -p $GETH_SECONDARY_PORT:$GETH_SECONDARY_PORT ethereum/client-go:v1.14.5 \
    --verbosity 1 \
    --http.vhosts '*,localhost,host.docker.internal' \
    --http \
    --http.port $GETH_SECONDARY_PORT \
    --http.api eth,net,web3,debug \
    --http.corsdomain '*' \
    --http.addr "0.0.0.0" \
    --networkid $NETWORK_ID \
    --dev \
    --dev.period 0 \
    --allow-insecure-unlock \
    --rpc.allow-unprotected-txs \
    --dev.gaslimit 20000000)

  sleep 3
}

stop_all() {
  echo -e "\nStopping and removing geth and geth-with-erc7562-tracer containers..."
  docker stop $geth_container_id > /dev/null
  sleep 3
  docker rm $geth_container_id > /dev/null

  docker stop $geth_with_erc7562_tracer_container_id > /dev/null
  sleep 3
  docker rm $geth_with_erc7562_tracer_container_id > /dev/null

  exit 0
}

# Start geth and geth-erc7562-native-tracer
start_geth_with_erc7562_native_tracer
start_geth

trap stop_all SIGINT 
echo -e "Started dev geth-with-erc7562-tracer node at http://localhost:$GETH_DEFAULT_PORT on network $NETWORK_ID"
echo -e "Started dev geth node at http://localhost:$GETH_SECONDARY_PORT on network $NETWORK_ID\n"
echo -e "Press Ctrl+C to stop the geth dev nodes"
while true; do
  sleep 1
done