#!/bin/bash

# Private keys are default hardhat accounts.
export TRANSEPTOR_MNEMONIC='test test test test test test test test test test test junk'
export TRANSEPTOR_BENEFICIARY='0xd21934eD8eAf27a67f0A70042Af50A1D6d195E81'

# Simple script to run Transeptor after building from source
node ./packages/bundler-builder/dist/bundler-builder/src/index.js --txMode base --auto