name: Build, Lint, Test, and Build Docker Images(Dry run)

on:
  workflow_call:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack and set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.7.0 --activate
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build-docker-images:
    name: Build Docker Image(Dry run)
    runs-on: ubuntu-latest
    needs: build-lint-test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get short commit hash
        id: get_short_hash
        run: echo SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7) >> $GITHUB_ENV
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          file: ./Dockerfile
          push: false
          tags: |
            transeptorlabs/bundler:${{ env.SHORT_SHA }}
      - name: Verify Docker images
        run: |
          docker images
